### ISSUE TITLE
Images get corrupted when resized/cached

### ISSUE THREAD

**Issue by marcaddeo** [AOEpeople/Aoe_AmazonCdn#3]
I'm having an issue where images will get "corrupted" when they're resized.

Reproducing the issue:
- Add an image to a product, and save it. This will upload the original to S3.
- View the product in the front end (and thus the image). This will download the original from S3, create a resized version, and upload to the `media/catalog/product/cache/...` folder on S3.
- The resulting cached and resized image is now corrupted. 

For example:
This image shows a corrupted image 
![Corrupted Image](http://i.imgur.com/6sRrxKh.png)

And this image shows the original image (note how this one has red in it)
![Not so corrupted image](http://i.imgur.com/eC65g6J.png)

While creating these two images, I noticed that they're actually both cached... The difference is only the size. The small (corrupted) ones dimensions are `736x460` while the large one is `940x587`.

At first I thought this was an issue of my theme, but I disabled the CDN stuff and tried reuploading a completely different image and the image wasn't corrupted. Re-enabled the CDN stuff and tried again with a new image.. And the image corruption was back.

So somewhere along the lines in this plugin, the image is getting corrupted. Not sure where really.

One other thing I did notice, was that on S3 the original has a `Content-Type` of `image/png`, while the cached versions are `binary/octet-stream`. I've tried changing it to `image/jpeg` and that doesn't fix it either.

Have you experienced any similar issues to this?

**Comment by bastianccm** [comment]
Looks like a grayscale issue, not only the red color but also the yellow in the spotlight and the blueish windows are gray now.

**Comment by marcaddeo** [comment]
Any ideas what could cause such an issue? It's just really strange that it would only happen when I'm using S3 for file storage.

**Comment by fbrnc** [comment]
Hi @marcaddeo,
out of curiosity: did you ever find out what the problem was?
Cheers,
Fabrizio

**Comment by marcaddeo** [comment]
@fbrnc no I don't think I ever solved it, I think I just said I was going to save that problem for later and went back to using a `media` folder... But I am no longer working on that project any longer (or company), so I won't be going back to it :stuck_out_tongue:

**Comment by tom00** [comment]
Just discovered this issue here. It seems I found the problem and managed to fix it for myself.
The description you can find in here. https://github.com/AOEpeople/Aoe_AmazonCdn/issues/4

**Comment by tmotyl** [comment]
see pull request https://github.com/AOEpeople/Aoe_AmazonCdn/pull/5 for a fix
